# Worshop 2.1 Numpy

1. Скачайте этот ноутбук к себе.
2. Заполните пропущенные ячейки, отвечая на заданные вопросы. Там должен быть код! (если не сказано обратное)
3. Сохраните результат в своём гитхаб репозитории.

#### Полезная литература

- http://www.numpy.org/
- https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html
- https://docs.scipy.org/doc/numpy/user/quickstart.html

1) Импортировать numpy и написать версию

In [3]:
import numpy as np
print (np.__version__)

1.24.3


2) Создать нулевой вектор размера 10

In [4]:
a =  np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3) Создать вектор заполненный 7-ами размера 7

In [5]:
b = np.full(7, 7)
b

array([7, 7, 7, 7, 7, 7, 7])

4) Создать вектор заполненный четными числами от 10 до 100

In [6]:
c = np.arange(10, 102, 2)
c

array([ 10,  12,  14,  16,  18,  20,  22,  24,  26,  28,  30,  32,  34,
        36,  38,  40,  42,  44,  46,  48,  50,  52,  54,  56,  58,  60,
        62,  64,  66,  68,  70,  72,  74,  76,  78,  80,  82,  84,  86,
        88,  90,  92,  94,  96,  98, 100])

5) Создать массив случайных чисел и развернуть его задом наперёд

In [7]:
z =  np.random.random((10)) 
print(z)
z = z[::-1]
print(z)

[0.11181027 0.64329655 0.76812224 0.97675638 0.234936   0.9818619
 0.0574238  0.17521571 0.99641938 0.32651009]
[0.32651009 0.99641938 0.17521571 0.0574238  0.9818619  0.234936
 0.97675638 0.76812224 0.64329655 0.11181027]


6) Создать двумерную матрицу размера 3 на 3, заполненную числами от 0 до 9

In [8]:
Z = np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


7) Создать матрицу размера 4 на 4 с единицами на диагонали смещеной на один наверх.

In [9]:
b = np.eye(4, 4, 1)
b

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

8) Создать матрицу с числами в диапазоне от 1 до 4 по диагонали. В других ячейках матрицы должны быть семерки.

In [10]:
matrix = np.diag(np.arange(1, 5))
matrix[matrix == 0] = 7
print(matrix)


[[1 7 7 7]
 [7 2 7 7]
 [7 7 3 7]
 [7 7 7 4]]


9) Создать матрицу размера 5 на 5 заполненную чилами от 0 до 4 в строках.

In [11]:
matrix = np.tile(np.arange(5), (5, 1))
print(matrix)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


10) Создать матрицу случайных чисел размера 10 на 10 и отнять среднее по строкам из каждого элемента строки

In [12]:
matrix = np.random.rand(10, 10)
mean = np.mean(matrix, axis=1)
matrix -= mean[:, np.newaxis]
print(matrix)

[[ 0.23449639 -0.28866095 -0.41706574 -0.17651562 -0.12807253 -0.11791915
   0.13545946  0.16166988  0.52030555  0.07630271]
 [ 0.03259652 -0.03749398  0.17755055 -0.13555743 -0.40438948  0.41149746
   0.18360886  0.009082   -0.30087552  0.06398101]
 [ 0.35176687  0.22581849 -0.05057612 -0.41844076  0.22835619  0.39901517
   0.25788183 -0.30019746 -0.37229579 -0.32132842]
 [-0.21263941 -0.12744478  0.08409207 -0.34376342 -0.33502035  0.40858593
  -0.13625565  0.09290675  0.36054636  0.2089925 ]
 [-0.10630451  0.11108746  0.02424304 -0.04677922  0.27905698  0.24314498
   0.06574117 -0.16802977 -0.26397604 -0.13818408]
 [-0.23371103 -0.23456397 -0.22626706  0.04015236 -0.22618444  0.18491243
  -0.10008971  0.14120752  0.45592571  0.19861818]
 [-0.33515605 -0.09851122  0.46135052 -0.33377046 -0.08680234  0.25888275
   0.04948577  0.31104186 -0.07864641 -0.14787444]
 [-0.11836023  0.08348243 -0.25686632 -0.08766465  0.26171116  0.11828299
  -0.26513848 -0.05544969 -0.20198281  0.5219856 ]


11) Создать матрицу случайных чисел размера 10 на 10 и отнять медиану по столбцам из каждого элемента столбца  

In [ ]:
matrix = np.random.rand(10, 10)
median = np.median(matrix, axis=0)
matrix -= median
print(matrix)

12) Создать матрицу случайных чисел 5x5. Добавить к ней столбецы максимумов и минимумов по строкам. Получится матрица 5x7.  

In [12]:
matrix = np.random.rand(5, 5)
max_rows = np.max(matrix, axis=1)
min_rows = np.min(matrix, axis=1)
matrix = np.column_stack((matrix, max_rows, min_rows))
print(matrix)

[[0.97074339 0.17396904 0.18224748 0.53436343 0.20357563 0.97074339
  0.17396904]
 [0.44465865 0.39587106 0.33232853 0.09811656 0.17788519 0.44465865
  0.09811656]
 [0.28479326 0.32256493 0.14083694 0.50944858 0.7914634  0.7914634
  0.14083694]
 [0.88849132 0.34180356 0.19829193 0.96901984 0.93604313 0.96901984
  0.19829193]
 [0.92711132 0.51868822 0.34084964 0.52701846 0.77899796 0.92711132
  0.34084964]]


13) Вектор чисел от 1 до 51 преобразовать в вектор нечетных чисел и в вектор четных чисел, поменять их размерности, чтобы получились две матрица. Найти произведение этих матриц. Найти обратную матрицу эётого произведения.  

In [41]:
vector = np.array(range(1, 51))
odd_vector = vector[vector % 2 != 0]
print(odd_vector)
even_vector = vector[vector % 2 == 0]
print(even_vector)
odd_matrix = odd_vector.reshape((5, 5))
even_matrix = even_vector.reshape((5, 5))
product_matrix = np.dot(odd_matrix, even_matrix.T)
print(product_matrix)

np.linalg.inv(product_matrix)


[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]
[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50]
[[  190   440   690   940  1190]
 [  490  1240  1990  2740  3490]
 [  790  2040  3290  4540  5790]
 [ 1090  2840  4590  6340  8090]
 [ 1390  3640  5890  8140 10390]]


LinAlgError: Singular matrix

14) Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами. 

In [17]:
matrix = np.zeros((8, 8))
matrix[1::2, ::2] = 1
matrix[::2, 1::2] = 1
print(matrix)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]
